name: "Run test"
on:
  push:
    branches:
      - "test"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Build project
        run: |
            npm i \
            npm run build \
            npm run build:test \
