name: "Run test"
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - "test"
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install project
        run: npm i

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: "Build scripts"
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test project
        run: npm run build:test
